//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTesting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTesting.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;        &lt;span style=&quot;color:#3b6ac8&quot;&gt;private&lt;/span&gt; XElement &lt;span style=&quot;color:#c73a69&quot;&gt;CreateOutline&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;string&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;[]&lt;/span&gt; position&lt;span style=&quot;color:#323232&quot;&gt;,&lt;/span&gt; XElement children&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;        &lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLContent1 {
            get {
                return ResourceManager.GetString("HTMLContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;        &lt;span style=&quot;color:#3b6ac8&quot;&gt;private bool&lt;/span&gt; &lt;span style=&quot;color:#c73a69&quot;&gt;IsSelectedTextInline&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;string&lt;/span&gt; pageID&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;        &lt;span style=&quot;color:#323232&quot;&gt;{&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    3 &lt;/span&gt;            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLContent2 {
            get {
                return ResourceManager.GetString("HTMLContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;            &lt;span style=&quot;color:#3b6ac8&quot;&gt;if&lt;/span&gt; &lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;node &lt;span style=&quot;color:#323232&quot;&gt;!=&lt;/span&gt; &lt;span style=&quot;color:#3b6ac8&quot;&gt;null&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;            &lt;span style=&quot;color:#323232&quot;&gt;{&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    3 &lt;/span&gt;                &lt;span style=&quot;color:# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLContent3 {
            get {
                return ResourceManager.GetString("HTMLContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;        &lt;span style=&quot;color:#3b6ac8&quot;&gt;private bool&lt;/span&gt; &lt;span style=&quot;color:#c73a69&quot;&gt;IsSelectedTextInline&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;string&lt;/span&gt; pageID&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;        &lt;span style=&quot;color:#323232&quot;&gt;{&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    3 &lt;/span&gt;            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLContent4 {
            get {
                return ResourceManager.GetString("HTMLContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Page xmlns=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot;&gt;
        ///  &lt;Outline&gt;
        ///    &lt;Position x=&quot;198.0&quot; y=&quot;950.3999633789062&quot; /&gt;
        ///    &lt;Size width=&quot;1600&quot; height=&quot;200&quot; /&gt;
        ///    &lt;OEChildren&gt;
        ///      &lt;OE&gt;
        ///        &lt;Table bordersVisible=&quot;false&quot;&gt;
        ///          &lt;Columns&gt;
        ///            &lt;Column index=&quot;0&quot; width=&quot;40&quot; /&gt;
        ///            &lt;Column index=&quot;1&quot; width=&quot;1400&quot; /&gt;
        ///          &lt;/Columns&gt;
        ///          &lt;Row&gt;
        ///            &lt;Cell shadingColor=&quot;#F0F0F0&quot;&gt;
        ///              &lt;OEChildren&gt;
        ///                &lt;OE&gt;
        ///                  &lt;T&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output1 {
            get {
                return ResourceManager.GetString("Output1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T11:46:27.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output2 {
            get {
                return ResourceManager.GetString("Output2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:12:59.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output3 {
            get {
                return ResourceManager.GetString("Output3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:41:19.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output4 {
            get {
                return ResourceManager.GetString("Output4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T11:46:27.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page2 {
            get {
                return ResourceManager.GetString("Page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:12:59.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page3 {
            get {
                return ResourceManager.GetString("Page3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:41:19.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page4 {
            get {
                return ResourceManager.GetString("Page4", resourceCulture);
            }
        }
    }
}
