//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTesting {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTesting.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;        &lt;span style=&quot;color:#3b6ac8&quot;&gt;private&lt;/span&gt; XElement &lt;span style=&quot;color:#c73a69&quot;&gt;CreateOutline&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;string&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;[]&lt;/span&gt; position&lt;span style=&quot;color:#323232&quot;&gt;,&lt;/span&gt; XElement children&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;        &lt;s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HTMLContent1 {
            get {
                return ResourceManager.GetString("HTMLContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;        &lt;span style=&quot;color:#3b6ac8&quot;&gt;private bool&lt;/span&gt; &lt;span style=&quot;color:#c73a69&quot;&gt;IsSelectedTextInline&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;string&lt;/span&gt; pageID&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;        &lt;span style=&quot;color:#323232&quot;&gt;{&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    3 &lt;/span&gt;            &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HTMLContent2 {
            get {
                return ResourceManager.GetString("HTMLContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;            &lt;span style=&quot;color:#3b6ac8&quot;&gt;if&lt;/span&gt; &lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;node &lt;span style=&quot;color:#323232&quot;&gt;!=&lt;/span&gt; &lt;span style=&quot;color:#3b6ac8&quot;&gt;null&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;            &lt;span style=&quot;color:#323232&quot;&gt;{&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    3 &lt;/span&gt;                &lt;span style=&quot;color:# [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HTMLContent3 {
            get {
                return ResourceManager.GetString("HTMLContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;        &lt;span style=&quot;color:#3b6ac8&quot;&gt;private bool&lt;/span&gt; &lt;span style=&quot;color:#c73a69&quot;&gt;IsSelectedTextInline&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;string&lt;/span&gt; pageID&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;        &lt;span style=&quot;color:#323232&quot;&gt;{&lt;/span&gt;
        ///&lt;span style=&quot;color:#969696&quot;&gt;    3 &lt;/span&gt;            &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HTMLContent4 {
            get {
                return ResourceManager.GetString("HTMLContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt; &lt;span style=&quot;color:#3b6ac8&quot;&gt;if&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;(&lt;/span&gt;x&lt;span style=&quot;color:#323232&quot;&gt;==&lt;/span&gt;&lt;span style=&quot;color:#1094a0&quot;&gt;0&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;)&lt;/span&gt;{return null;}
        ///&lt;/pre&gt; 的本地化字符串。
        /// </summary>
        internal static string HTMLContent5 {
            get {
                return ResourceManager.GetString("HTMLContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;pre style=&quot;color:#323232; background-color:#ffffff; font-size:10pt; font-family:&apos;Courier New&apos;;&quot;&gt;&lt;span style=&quot;color:#969696&quot;&gt;    1 &lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;select&lt;/span&gt; x
        ///&lt;span style=&quot;color:#969696&quot;&gt;    2 &lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;From&lt;/span&gt; dual
        ///&lt;span style=&quot;color:#969696&quot;&gt;    3 &lt;/span&gt;&lt;span style=&quot;color:#3b6ac8&quot;&gt;Where&lt;/span&gt; x &lt;span style=&quot;color:#323232&quot;&gt;=&lt;/span&gt; &lt;span style=&quot;color:#1094a0&quot;&gt;1&lt;/span&gt;&lt;span style=&quot;color:#323232&quot;&gt;;&lt;/span&gt;
        ///&lt;/pre&gt; 的本地化字符串。
        /// </summary>
        internal static string HTMLContent6 {
            get {
                return ResourceManager.GetString("HTMLContent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Page xmlns=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot;&gt;
        ///  &lt;Outline&gt;
        ///    &lt;Position x=&quot;198.0&quot; y=&quot;950.3999633789062&quot; /&gt;
        ///    &lt;Size width=&quot;1600&quot; height=&quot;200&quot; /&gt;
        ///    &lt;OEChildren&gt;
        ///      &lt;OE&gt;
        ///        &lt;Table bordersVisible=&quot;false&quot;&gt;
        ///          &lt;Columns&gt;
        ///            &lt;Column index=&quot;0&quot; width=&quot;40&quot; /&gt;
        ///            &lt;Column index=&quot;1&quot; width=&quot;1400&quot; /&gt;
        ///          &lt;/Columns&gt;
        ///          &lt;Row&gt;
        ///            &lt;Cell shadingColor=&quot;#F0F0F0&quot;&gt;
        ///              &lt;OEChildren&gt;
        ///                &lt;OE&gt;
        ///                  &lt;T&gt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Output1 {
            get {
                return ResourceManager.GetString("Output1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T11:46:27.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Output2 {
            get {
                return ResourceManager.GetString("Output2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:12:59.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Output3 {
            get {
                return ResourceManager.GetString("Output3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:41:19.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Output4 {
            get {
                return ResourceManager.GetString("Output4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:55:20.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Output5 {
            get {
                return ResourceManager.GetString("Output5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:56:54.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Output6 {
            get {
                return ResourceManager.GetString("Output6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T11:46:27.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page2 {
            get {
                return ResourceManager.GetString("Page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:12:59.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page3 {
            get {
                return ResourceManager.GetString("Page3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:41:19.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page4 {
            get {
                return ResourceManager.GetString("Page4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:55:20.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page5 {
            get {
                return ResourceManager.GetString("Page5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot; ID=&quot;{62B9E873-2769-000C-184C-3F76DBF14255}{1}{E1956852926608929975371947232731342679241291}&quot; name=&quot;1&quot; dateTime=&quot;2017-08-11T11:43:50.000Z&quot; lastModifiedTime=&quot;2018-02-14T13:56:54.000Z&quot; pageLevel=&quot;1&quot; isCurrentlyViewed=&quot;true&quot; selected=&quot;partial&quot; lang=&quot;la&quot;&gt;
        ///  &lt;one:QuickStyleDef index=&quot;0&quot; name=&quot;PageTitle&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;automatic&quot; font=&quot;Calibri Light&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;0.0&quot; spaceAfter=&quot;0.0&quot; /&gt;
        ///  &lt;one:Q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page6 {
            get {
                return ResourceManager.GetString("Page6", resourceCulture);
            }
        }
    }
}
